env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-console: off
  import/extensions: [warn, { js: ignorePackages }]
  no-underscore-dangle: [warn, { allow: ["__filename", "__dirname"] }]
  prettier/prettier: [error]
