name: tests-check

on: push
jobs:
  tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Node setup'
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: 'Install packages'
        run: make install

      - name: 'Run tests'
        run: make test
